BREED_REFERENCE = {
    "1": "affenpinscher",
    "2": "afghan hound",
    "3": "airedale terrier",
    "4": "akita",
    "5": "alaskan malamute",
    "6": "american english coonhound",
    "7": "american eskimo dog",
    "8": "american foxhound",
    "9": "american hairless terrier",
    "10": "american leopard hound",
    "11": "american staffordshire terrier",
    "12": "american water spaniel",
    "13": "anatolian shepherd dog",
    "14": "appenzeller sennenhunde",
    "15": "australian cattle dog",
    "16": "australian shepherd",
    "17": "australian terrier",
    "18": "azawakh",
    "19": "barbet",
    "20": "basenji",
    "21": "basset fauve de bretagne",
    "22": "basset hound",
    "23": "bavarian mountain scent hound",
    "24": "beagle",
    "25": "bearded collie",
    "26": "beauceron",
    "27": "bedlington terrier",
    "28": "belgian laekenois",
    "29": "belgian malinois",
    "30": "belgian sheepdog",
    "31": "belgian tervuren",
    "32": "bergamasco sheepdog",
    "33": "berger picard",
    "34": "bernese mountain dog",
    "35": "bichon frise",
    "36": "biewer terrier",
    "37": "black and tan coonhound",
    "38": "black russian terrier",
    "39": "bloodhound",
    "40": "bluetick coonhound",
    "41": "boerboel",
    "42": "bolognese",
    "43": "border collie",
    "44": "border terrier",
    "45": "borzoi",
    "46": "boston terrier",
    "47": "bouvier des flandres",
    "48": "boxer",
    "49": "boykin spaniel",
    "50": "briard",
    "51": "brittany",
    "52": "brussels griffon",
    "53": "bull terrrier",
    "54": "bull terrier (miniature)",
    "55": "bulldog",
    "56": "bullmastiff",
    "57": "cairn terrier",
    "58": "canaan dog",
    "59": "cane corso",
    "60": "cardigan welsh corgi",
    "61": "cavalier king charles spaniel",
    "62": "cesky terrier",
    "63": "chesapeake bay retriever",
    "64": "chihuahua",
    "65": "chinese crested dog",
    "66": "chinese shar pei",
    "67": "chinook",
    "68": "chow chow",
    "69": "cirneco dell'etna",
    "70": "clumber spaniel",
    "71": "cocker spaniel",
    "72": "collie",
    "73": "coton de tulear",
    "74": "curly-coated retriever",
    "75": "dachshund",
    "76": "dalmatian",
    "77": "dandie dinmont terrier",
    "78": "doberman pinscher",
    "79": "doque de bordeaux",
    "80": "english cocker spaniel",
    "81": "english foxhound",
    "82": "english setter",
    "83": "english springer spaniel",
    "84": "english toy spaniel",
    "85": "entlebucher mountain dog",
    "86": "field spaniel",
    "87": "finnish lapphund",
    "88": "finnish spitz",
    "89": "flat-coated retriever",
    "90": "french bulldog",
    "91": "german pinscher",
    "92": "german shepherd dog",
    "93": "german shorthaired pointer",
    "94": "german wirehaired pointer",
    "95": "giant schnauzer",
    "96": "glen of imaal terrier",
    "97": "golden retriever",
    "98": "gordon setter",
    "99": "great dane",
    "100": "great pyrenees",
    "101": "greater swiss mountain dog",
    "102": "greyhound",
    "103": "harrier",
    "104": "havanese",
    "105": "ibizan hound",
    "106": "icelandic sheepdog",
    "107": "irish red and white setter",
    "108": "irish setter",
    "109": "irish terrier",
    "110": "irish water spaniel",
    "111": "irish wolfhound",
    "112": "itialian greyhound",
    "113": "japanese chin",
    "114": "keeshond",
    "115": "kerry blue terrier",
    "116": "komondor",
    "117": "kuvasz",
    "118": "labrador retriever",
    "119": "lagotto romagnolo",
    "120": "lakeland terrier",
    "121": "leonberger",
    "122": "lhasa apso",
    "123": "lowchen",
    "124": "maltese",
    "125": "manchester terrier",
    "126": "mastiff",
    "127": "miniature american shepherd",
    "128": "miniature bull terrier",
    "129": "miniature pinscher",
    "130": "miniature schnauzer",
    "131": "neapolitan mastiff",
    "132": "newfoundland",
    "133": "norfolk terrier",
    "134": "norwegian buhund",
    "135": "norwegian elkhound",
    "136": "norwegian lundehund",
    "137": "norwich terrier",
    "138": "nova scotia duck-tolling retriever",
    "139": "old english sheepdog",
    "140": "otterhound",
    "141": "papillon",
    "142": "parson russell terrier",
    "143": "pekingese",
    "144": "pembroke welsh corgi",
    "145": "petit basset griffon vendeen",
    "146": "pharaoh hound",
    "147": "plott",
    "148": "pointer",
    "149": "polish lowland sheepdog",
    "150": "pomeranian",
    "151": "poodle",
    "152": "portuguese podengo",
    "153": "portuguese water dog",
    "154": "pug",
    "155": "puli",
    "156": "pumi",
    "157": "pyrenean shepherd",
    "158": "rat terrier",
    "159": "redbone coonhound",
    "160": "rhodesian ridgeback",
    "161": "rottweiler",
    "162": "russel terrier",
    "163": "st. benard",
    "164": "saluki",
    "165": "samoyed",
    "201": "schapendoes",
    "166": "schipperke",
    "167": "scottish deerhound",
    "168": "scottish terrier",
    "169": "sealyham terrier",
    "170": "shetland sheepdog",
    "171": "shiba inu",
    "172": "shih tzu",
    "173": "siberian husky",
    "174": "silky terrier",
    "175": "skye terrier",
    "176": "sloughi",
    "177": "smooth fox terrier",
    "178": "soft-coated wheaten terrier",
    "179": "spanish water dog",
    "180": "spinone italiano",
    "181": "staffordshire bull terrier",
    "182": "standard schnauzer",
    "183": "sussex spaniel",
    "184": "swedish valhund",
    "185": "tibetan mastiff",
    "186": "tibetan spaniel",
    "187": "tibetan terrier",
    "188": "toy fox terrier",
    "189": "treeing water coonhound",
    "190": "vizsla",
    "191": "weimaraner",
    "192": "welsh springer spaniel",
    "193": "welsh terrier",
    "194": "west highland white terrier",
    "195": "whippet",
    "196": "wire fox terrier",
    "197": "wirehaired pointing griffon",
    "198": "wirehaired vizsla",
    "199": "xoloitzcuintli",
    "200": "yorkshire terrier",
}